version: '3.8'

services:
  app:
    container_name: ${PROJECT_NAME:-fast-links}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - app-data:/data
    environment:
      - PORT=8080
      - DATA_FILE_PATH=/data/data.db
    restart: unless-stopped

# Definiujemy wolumen Docker
volumes:
  app-data:
